### ISSUE TITLE
Missing label and doc elements on workflow inputs considered as errors

### ISSUE THREAD

**Issue by bevalentin** [EOEPCA/app-package-validation#1]
Hi,

The Validator considers missing `label` and `doc` elements on workflow inputs as errors (due to requirement 10).

```
Missing element for input 'in1' of Workflow 'workflow': label
Missing element for input 'in1' of Workflow 'workflow': doc
```

This would mean that without these elements an AP CWL is invalid and cannot be executed by an EOEPCA ADES.

It is however not the case: The EOEPCA ADES can execute AP CWL that are missing these elements.
Either the ADES should fail or the severity must be lowered (e.g. reported as a `hint`).

**Comment by fabricebrito** [comment]
It's the OGC BP driving the validator, not the EOEPCA ADES behaviour
