### ISSUE TITLE
Inputs of type Directory[] not validated as inputs of type Directory

### ISSUE THREAD

**Issue by bevalentin** [EOEPCA/app-package-validation#2]
Hi,

When a CommandLineTool or a Workflow has an input of type `Directory[]` (and no input of type `Directory`), the following hints are included in the validation report (due to requirements 12 and 13, respectively):

```
No input of type 'Directory' for CommandLineTool 'clt1'; make sure inputs referencing GeoJSON features of EO products that need to be staged in are of type 'Directory'
No input of type 'Directory' for Workflow 'workflow'; make sure inputs referencing GeoJSON features of EO products that need to be staged in are of type 'Directory'
```

When `Directory[]` inputs are used, stage-in is executed to fetch the related EO products. So these hints are not correct.

**Comment by fabricebrito** [comment]
@floeschau this needs a fix

**Comment by michele-longobardo-t2** [comment]
@floeschau cc @fabricebrito I committed the needed changes on develop, please review it and share the green flag for the main branch merge. 
The last commit fixes also the other issue related to the "type_" since cwl-utils 0.30.0

**Comment by floeschau** [comment]
The new version 0.5.0 fixes this issue.
