### ISSUE TITLE
The AP Validator fails using cwl-utils 0.30.0

### ISSUE THREAD

**Issue by bevalentin** [EOEPCA/app-package-validation#3]
Hi, 

The AP Validator requires `cwltool` which itself requires `cwl-utils >= 0.22`.
A recent change in `cwl-utils` 0.30.0 (tagged on 26-Oct-2023) breaks the validation.
In several classes, they have changed the attribute `type` to `type_`.
For example in [`CommandInputParameter`](https://github.com/common-workflow-language/cwl-utils/blob/v0.30/cwl_utils/parser/cwl_v1_0.py#L10539) and [`CommandOutputParameter`](https://github.com/common-workflow-language/cwl-utils/blob/v0.30/cwl_utils/parser/cwl_v1_0.py#L11151), bus also in `WorkflowInputParameter` and `WorkflowOutputParameter`.
It seems to apply to all CWL versions (1.0, 1.1 and 1.2).
The AP Validator works fine with `cwl-utils` version 0.29.0.

**Comment by michele-longobardo-t2** [comment]
@floeschau  with 0.5.0 version you can close also this

**Comment by michele-longobardo-t2** [comment]
fixed in 0.5.0
